# Travis  is a continuous integration service to build, test and deploy the package

# adapted from https://github.com/scikit-learn/scikit-learn/blob/master/.travis.yml

# use travis only on the following branches for building
branches:
  only:
    - master
    - dev
    - /^v[0-9]+\.[0-9]+\.[0-9]+/  # allow builds on tags

language: shell  # 'language: python' is an error on Travis CI with macOS

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache

dist: xenial  # Ubuntu 16.04

env:
  global:
    - DEPLOY_BRANCH="master"  # branch on which to deploy build artifacts and website
    - DEPLOY_JOB_NAME="osx-py37"  # job on which to deploy website

    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

    - TEST_DIR=/tmp/sktime  # Directory where tests are run from
    - REQUIREMENTS=build_tools/requirements.txt
    - COVERAGE=true

# platforms and package environments to test
jobs:
  include:
    - name: "osx-py36"
      os: osx
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA_VERSION=Miniconda3-latest-MacOSX-x86_64.sh
    - name: "osx-py37"
      os: osx
      env:
        - PYTHON_VERSION=3.7
        - MINICONDA_VERSION=Miniconda3-latest-MacOSX-x86_64.sh
    - name: "osx-py38"
      os: osx
      env:
        - PYTHON_VERSION=3.8
        # Check available miniconda version: https://repo.anaconda.com/miniconda/
        - MINICONDA_VERSION=Miniconda3-py38_4.8.2-MacOSX-x86_64.sh

addons:
  # travis recommends to specify any additional necessary packages here,
  # rather than manually installing them in the install script
  homebrew:
    packages:
      - ccache
      - libomp
      - jq
      - pandoc
    update: true

install:
  # build and install sktime
  - source build_tools/travis/install.sh

script:
  # run unit tests
  - bash build_tools/travis/test_script.sh

after_success:
  # generate docs
  - bash build_tools/travis/after_success.sh

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:

# Docs are no longer deployed via travis but now instead via readthedocs
#  # deploy website on master branch
#  - provider: pages
#    skip_cleanup: true  # skip clean up which would delete build artifacts
#    local_dir: "./docs/_build/html"
#    github_token: $GITHUB_TOKEN  # Generated in Github settings page of your repo, set in travis settings
#    keep_history: false
#    fqdn: sktime.org  # set custom domain
#    on:
#      branch: $DEPLOY_BRANCH  # deploy only on master
#      condition: $TRAVIS_JOB_NAME = $DEPLOY_JOB_NAME  # deploy only on macOS build

#  # release is deployed only on tagged commits on master
#  - provider: releases
#    skip_cleanup: true
#    api_key: $GITHUB_TOKEN
#    draft: true
#    file_glob: true  # enable wildcards in file
#    file: dist/*  # files to upload
#    on:
#      tags: true  # deploy only on tags

  # deploy to pypi on tagged commits on master
  - provider: pypi
    skip_cleanup: true
    username: "__token__"
    password: $PYPI_PASSWORD
    skip_existing: true
    on:
      tags: true
