# whitelist the following branches for building
branches:
  only:
    - master
    - dev

env:
  global:
    - TEST_DIR=tmp/
    - REQUIREMENTS=build_tools/requirements.txt
    - TEST_SLOW=false

dist: xenial
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    # add more combinations here as per requirement
    - env: PYTHON_VERSION="3.6" TF_VERSION="1.9"
    - env: PYTHON_VERSION="3.6" TF_VERSION="1.15"
    - env: PYTHON_VERSION="3.7" TF_VERSION="2.1"
    - env: PYTHON_VERSION="3.7" TF_VERSION="2.3"

install:
  # Download and install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH

  # Build
  - source build_tools/build.sh

script:
  - source build_tools/test.sh

after_success:
  - coveralls



